/**
 * commitlint.mjs
 * Validates commit messages against the Conventional Commits spec.
 * https://www.conventionalcommits.org/en/v1.0.0/
 *
 * Format: <type>(<optional-scope>): <description>
 *
 * Examples (valid):
 *   feat: add user authentication
 *   fix(auth): resolve token expiration bug
 *   chore!: drop Node 18 support
 *   docs(readme): update setup instructions
 */

import { readFileSync } from 'fs';
import chalk from 'chalk';

const ALLOWED_TYPES = [
  'feat',
  'fix',
  'docs',
  'style',
  'refactor',
  'perf',
  'test',
  'build',
  'ci',
  'chore',
  'revert',
  'wip',
];

// type(scope)!: description
// Scope allows: lowercase letters, digits, hyphens, slashes, commas, and spaces
const COMMIT_PATTERN = new RegExp(
  `^(${ALLOWED_TYPES.join('|')})(\\([a-z0-9\\-/,\\s]+\\))?(!)?:\\s.{1,100}$`
);

const commitMsgFile = process.argv[2];

if (!commitMsgFile) {
  console.error(chalk.red('✖ commitlint: No commit message file path provided.'));
  process.exit(1);
}

const commitMsg = readFileSync(commitMsgFile, 'utf-8').trim();

// Skip merge commits, revert commits auto-generated by git, and fixup/squash
if (
  commitMsg.startsWith('Merge ') ||
  commitMsg.startsWith('Revert "') ||
  commitMsg.startsWith('fixup! ') ||
  commitMsg.startsWith('squash! ')
) {
  process.exit(0);
}

// Skip lines starting with # (git comment lines)
const firstLine = commitMsg.split('\n').find((line) => !line.startsWith('#')) ?? '';

if (!COMMIT_PATTERN.test(firstLine)) {
  console.error(`
${chalk.red.bold('✖ Invalid commit message format')}
${chalk.dim('─'.repeat(50))}

${chalk.red('  Message:')} ${chalk.yellow(firstLine || '(empty)')}

${chalk.bold('  Expected format:')}
  ${chalk.green('<type>(<optional-scope>): <short description>')}

${chalk.bold('  Allowed types:')}
  ${ALLOWED_TYPES.map((t) => chalk.cyan(t)).join(', ')}

${chalk.bold('  Valid examples:')}
  ${chalk.green('feat: add login page')}
  ${chalk.green('fix(auth): resolve token refresh issue')}
  ${chalk.green('chore!: drop Node 18 support  (! = breaking change)')}
  ${chalk.green('docs(readme): update development guide')}

${chalk.dim('  To bypass (emergency only): git commit --no-verify')}
`);
  process.exit(1);
}

process.exit(0);
